### ISSUE TITLE
DOTS Collisions?

### ISSUE THREAD

**Issue by PrakashNep** [DreamersIncStudios/ECS-Motion-System#12]
Hi.
After adding DOTS Physics to the character and the test environment, the character passes through the environment without collisions unless the ConvertToEntity script is set to Destroy (which ofc takes away all the inputs, but just a matter of test). What are your thoughts on having DOTS Physics? 
Regards.

**Comment by DreamersIncStudios** [comment]
This repo is designed in support of an Action RPG Title currently in production code named Project Rebirth. At this time, neither Project Rebirth or the ECS Motion System do not require DOTS Physics. Because the preview nature of DOTS, where things are constantly changing and being update, the focus is to use what is needed to complete the task. So until default Physics system becomes a major performance limit or we need to use DOTS Physics, we will not be pursuing DOTS Physics
